version: "3.7"
services:
  mysql-service:
    image: mysql:latest
    networks:
      - spring-boot-mysql-network
    restart: always
    environment:
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=api_rest
  web-service:
    build:
      context: ./rest
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - spring-boot-mysql-network
    depends_on:
      - mysql-service
networks:
  spring-boot-mysql-network:
    driver: bridge
